### PR TITLE
Adding Blog Content

### PR DESCRIPTION
**Pull request by dpb587**
This branch contains changes for adding a blog. It includes sample (simple) blog posts as a reference, and also a [creating blog posts doc](https://github.com/logsearch/logsearch-website/blob/adding-blog-content/docs/website/guides/creating-a-blog-post.md). It should be ready to merge - it's just waiting for someone to write an actual blog post instead of my two useless stubs.

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/12/Test PASSed.

**Comment by dpb587** [comment]
@mrdavidlaing, you can take over from here (in terms of writing an actual blog post, deleting my samples, and merging).

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/14/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/15/Test PASSed.

**Comment by mrdavidlaing** [comment]
@dpb587 - thanks!  2 new blog posts added - http://logsearch-website-pr8.apps.cityindex.logsearch.io/blog/

**Pull request merged**
