### PR TITLE
Add standard bin/scripts

### PR DESCRIPTION
**Pull request by mrdavidlaing**
This PR implements the standard build entrypoints / menu under `bin/`, specifically:

* `bin/build` <-- builds the jekyll site to `_site/`
* `bin/package  artifact.tgz` <-- does a clean build of the jekyll site inside a Docker container, and tars the resulting `_site/` files
* `bin/reload-upstream` <-- fetches upstream doc repositories
* `bin/start-webserver` <-- runs a local webserver serving the site for development uses

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/11/

**Build Log**
*last 50 lines*

 ```
[EnvInject] - Inject global passwords.
GitHub pull request #7 of commit fe29510281104ea718e0591ace305b8baa6021fe automatically merged.
[EnvInject] - Loading node environment variables.
Building remotely on slave-z0.0 (docker ubuntu swarm) in workspace /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/logsearch/logsearch-website.git # timeout=10
Fetching upstream changes from https://github.com/logsearch/logsearch-website.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.helper store --file=/tmp/git466979246488236266.credentials # timeout=10
 > git fetch --tags --progress https://github.com/logsearch/logsearch-website.git +refs/pull/*:refs/remotes/origin/pr/*
 > git config --local --remove-section credential # timeout=10
 > git rev-parse origin/pr/7/merge^{commit} # timeout=10
Checking out Revision 13812c3ddd3faac5764244af6713b19c7eb3de5e (detached)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 13812c3ddd3faac5764244af6713b19c7eb3de5e
First time build. Skipping changelog.
[shared.releases.logsearch-website-PRs] $ /bin/sh -xe /tmp/hudson6500193838790253752.sh
+ /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/_build/bin/jenkins-build logsearch-website-11.tar.gz
/tmp/hudson6500193838790253752.sh: 2: /tmp/hudson6500193838790253752.sh: /var/vcap/sys/tmp/jenkins_slave/workspace/shared.releases.logsearch-website-PRs/_build/bin/jenkins-build: not found
Build step 'Execute shell' marked build as failure
```
Test FAILed.

**Comment by mrdavidlaing** [comment]
@dpb587, Great feedback, thanks.  I especially like the idea that `start-` indicates a background process and `run-` indicates a foreground process.

I've made all the changes propose.

**Comment by sopel** [comment]
:+1:

**Comment by mrdavidlaing** [comment]
retest this please

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearch-website-PRs/13/Test PASSed.

**Pull request merged**
